"""init

Revision ID: 603b2ecc06a8
Revises:
Create Date: 2026-05-07 16:54:19.572350

"""

# ruff: noqa: E501, PLR0915

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "603b2ecc06a8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "graphs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_graphs_id"), "graphs", ["id"], unique=False)
    op.create_table(
        "osint_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_osint_sources_id"), "osint_sources", ["id"], unique=False)
    op.create_index(op.f("ix_osint_sources_name"), "osint_sources", ["name"], unique=False)
    op.create_table(
        "person_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("date_of_birth", sa.String(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("nationality", sa.String(), nullable=True),
        sa.Column("id_number", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("occupation", sa.String(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_person_records_first_name"), "person_records", ["first_name"], unique=False
    )
    op.create_index(op.f("ix_person_records_id"), "person_records", ["id"], unique=False)
    op.create_index(
        op.f("ix_person_records_id_number"), "person_records", ["id_number"], unique=False
    )
    op.create_index(
        op.f("ix_person_records_last_name"), "person_records", ["last_name"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "news",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("full_text", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("named_entities", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["osint_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("link", name="uq_news_link"),
    )
    op.create_index(op.f("ix_news_fetched_at"), "news", ["fetched_at"], unique=False)
    op.create_index(op.f("ix_news_id"), "news", ["id"], unique=False)
    op.create_index(op.f("ix_news_link"), "news", ["link"], unique=False)
    op.create_index(op.f("ix_news_published_at"), "news", ["published_at"], unique=False)
    op.create_index(op.f("ix_news_source_id"), "news", ["source_id"], unique=False)
    op.create_index(
        "ix_news_source_published_at", "news", ["source_id", "published_at"], unique=False
    )
    op.create_table(
        "nodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("graph_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["graph_id"],
            ["graphs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_nodes_id"), "nodes", ["id"], unique=False)
    op.create_table(
        "record_addresses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["person_records.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_record_addresses_id"), "record_addresses", ["id"], unique=False)
    op.create_table(
        "record_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("file_type", sa.String(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["person_records.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_record_documents_id"), "record_documents", ["id"], unique=False)
    op.create_table(
        "record_phones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["person_records.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_record_phones_id"), "record_phones", ["id"], unique=False)
    op.create_index(
        op.f("ix_record_phones_phone_number"), "record_phones", ["phone_number"], unique=False
    )
    op.create_table(
        "record_social_media",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("username_or_url", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["person_records.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_record_social_media_id"), "record_social_media", ["id"], unique=False)
    op.create_table(
        "word_lists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("graph_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("keywords", sa.JSON(), nullable=True),
        sa.Column("people", sa.JSON(), nullable=True),
        sa.Column("organizations", sa.JSON(), nullable=True),
        sa.Column("locations", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["graph_id"],
            ["graphs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_word_lists_graph_id"), "word_lists", ["graph_id"], unique=False)
    op.create_index(op.f("ix_word_lists_id"), "word_lists", ["id"], unique=False)
    op.create_index("ix_word_lists_status", "word_lists", ["status"], unique=False)
    op.create_index("ix_word_lists_updated", "word_lists", ["updated_at"], unique=False)
    op.create_table(
        "notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("news_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["news_id"],
            ["news.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notes_id"), "notes", ["id"], unique=False)
    op.create_table(
        "relationships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("graph_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["graph_id"],
            ["graphs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_relationships_id"), "relationships", ["id"], unique=False)
    op.create_table(
        "word_list_alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word_list_id", sa.Integer(), nullable=False),
        sa.Column("news_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("match_terms", sa.JSON(), nullable=True),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["news_id"],
            ["news.id"],
        ),
        sa.ForeignKeyConstraint(
            ["word_list_id"],
            ["word_lists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("word_list_id", "news_id", name="uq_word_list_alert_news"),
    )
    op.create_index("ix_word_list_alerts_created", "word_list_alerts", ["created_at"], unique=False)
    op.create_index(op.f("ix_word_list_alerts_id"), "word_list_alerts", ["id"], unique=False)
    op.create_index(
        "ix_word_list_alerts_list_read",
        "word_list_alerts",
        ["word_list_id", "is_read"],
        unique=False,
    )
    op.create_index(
        op.f("ix_word_list_alerts_news_id"), "word_list_alerts", ["news_id"], unique=False
    )
    op.create_index(
        op.f("ix_word_list_alerts_word_list_id"), "word_list_alerts", ["word_list_id"], unique=False
    )
    op.create_table(
        "word_list_news",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word_list_id", sa.Integer(), nullable=False),
        sa.Column("news_id", sa.Integer(), nullable=False),
        sa.Column("match_terms", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["news_id"],
            ["news.id"],
        ),
        sa.ForeignKeyConstraint(
            ["word_list_id"],
            ["word_lists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("word_list_id", "news_id", name="uq_word_list_news"),
    )
    op.create_index(
        "ix_word_list_news_created", "word_list_news", ["word_list_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_word_list_news_id"), "word_list_news", ["id"], unique=False)
    op.create_index(op.f("ix_word_list_news_news_id"), "word_list_news", ["news_id"], unique=False)
    op.create_index(
        op.f("ix_word_list_news_word_list_id"), "word_list_news", ["word_list_id"], unique=False
    )
    op.create_table(
        "note_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("note_id", sa.Integer(), nullable=True),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["notes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_note_images_id"), "note_images", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_note_images_id"), table_name="note_images")
    op.drop_table("note_images")
    op.drop_index(op.f("ix_word_list_news_word_list_id"), table_name="word_list_news")
    op.drop_index(op.f("ix_word_list_news_news_id"), table_name="word_list_news")
    op.drop_index(op.f("ix_word_list_news_id"), table_name="word_list_news")
    op.drop_index("ix_word_list_news_created", table_name="word_list_news")
    op.drop_table("word_list_news")
    op.drop_index(op.f("ix_word_list_alerts_word_list_id"), table_name="word_list_alerts")
    op.drop_index(op.f("ix_word_list_alerts_news_id"), table_name="word_list_alerts")
    op.drop_index("ix_word_list_alerts_list_read", table_name="word_list_alerts")
    op.drop_index(op.f("ix_word_list_alerts_id"), table_name="word_list_alerts")
    op.drop_index("ix_word_list_alerts_created", table_name="word_list_alerts")
    op.drop_table("word_list_alerts")
    op.drop_index(op.f("ix_relationships_id"), table_name="relationships")
    op.drop_table("relationships")
    op.drop_index(op.f("ix_notes_id"), table_name="notes")
    op.drop_table("notes")
    op.drop_index("ix_word_lists_updated", table_name="word_lists")
    op.drop_index("ix_word_lists_status", table_name="word_lists")
    op.drop_index(op.f("ix_word_lists_id"), table_name="word_lists")
    op.drop_index(op.f("ix_word_lists_graph_id"), table_name="word_lists")
    op.drop_table("word_lists")
    op.drop_index(op.f("ix_record_social_media_id"), table_name="record_social_media")
    op.drop_table("record_social_media")
    op.drop_index(op.f("ix_record_phones_phone_number"), table_name="record_phones")
    op.drop_index(op.f("ix_record_phones_id"), table_name="record_phones")
    op.drop_table("record_phones")
    op.drop_index(op.f("ix_record_documents_id"), table_name="record_documents")
    op.drop_table("record_documents")
    op.drop_index(op.f("ix_record_addresses_id"), table_name="record_addresses")
    op.drop_table("record_addresses")
    op.drop_index(op.f("ix_nodes_id"), table_name="nodes")
    op.drop_table("nodes")
    op.drop_index("ix_news_source_published_at", table_name="news")
    op.drop_index(op.f("ix_news_source_id"), table_name="news")
    op.drop_index(op.f("ix_news_published_at"), table_name="news")
    op.drop_index(op.f("ix_news_link"), table_name="news")
    op.drop_index(op.f("ix_news_id"), table_name="news")
    op.drop_index(op.f("ix_news_fetched_at"), table_name="news")
    op.drop_table("news")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_person_records_last_name"), table_name="person_records")
    op.drop_index(op.f("ix_person_records_id_number"), table_name="person_records")
    op.drop_index(op.f("ix_person_records_id"), table_name="person_records")
    op.drop_index(op.f("ix_person_records_first_name"), table_name="person_records")
    op.drop_table("person_records")
    op.drop_index(op.f("ix_osint_sources_name"), table_name="osint_sources")
    op.drop_index(op.f("ix_osint_sources_id"), table_name="osint_sources")
    op.drop_table("osint_sources")
    op.drop_index(op.f("ix_graphs_id"), table_name="graphs")
    op.drop_table("graphs")
    # ### end Alembic commands ###
